Upgrade to avko-n refsw
Change-Id: I7bd630f18709e7f8942cbfacedee4c01f9b6684c

diff --git a/BSEAV/app/atlas/build/Makefile b/BSEAV/app/atlas/build/Makefile
--- a/BSEAV/app/atlas/build/Makefile
+++ b/BSEAV/app/atlas/build/Makefile
@@ -1,43 +1,39 @@
 #############################################################################
 # Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 #
-# This program is the proprietary software of Broadcom and/or its
-# licensors, and may only be used, duplicated, modified or distributed pursuant
-# to the terms and conditions of a separate, written license agreement executed
-# between you and Broadcom (an "Authorized License").  Except as set forth in
-# an Authorized License, Broadcom grants no license (express or implied), right
-# to use, or waiver of any kind with respect to the Software, and Broadcom
-# expressly reserves all rights in and to the Software and all intellectual
-# property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
+# This program is the proprietary software of Broadcom and/or its licensors,
+# and may only be used, duplicated, modified or distributed pursuant to the terms and
+# conditions of a separate, written license agreement executed between you and Broadcom
+# (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
+# no license (express or implied), right to use, or waiver of any kind with respect to the
+# Software, and Broadcom expressly reserves all rights in and to the Software and all
+# intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 # HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 # NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 #
 # Except as expressly set forth in the Authorized License,
 #
-# 1. This program, including its structure, sequence and organization,
-#    constitutes the valuable trade secrets of Broadcom, and you shall use all
-#    reasonable efforts to protect the confidentiality thereof, and to use
-#    this information only in connection with your use of Broadcom integrated
-#    circuit products.
+# 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
+# secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
+# and to use this information only in connection with your use of Broadcom integrated circuit products.
 #
-# 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
-#    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
-#    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
-#    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
-#    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
-#    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
-#    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
-#    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
+# 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
+# AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
+# WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
+# THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
+# OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
+# LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
+# OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
+# USE OR PERFORMANCE OF THE SOFTWARE.
 #
-# 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
-#    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
-#    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
-#    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
-#    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
-#    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
-#    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
-#    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
-#
+# 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
+# LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
+# EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
+# USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
+# THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
+# ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
+# LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
+# ANY LIMITED REMEDY.
 #############################################################################
 
 
@@ -396,6 +392,7 @@ APP_OBJECTS += \
     channel_sat.o \
     channel_ofdm.o \
     channel_playback.o \
+    channel_mosaic.o \
     crypto.o \
     videolist.o \
     playback.o \
@@ -460,7 +457,9 @@ APP_OBJECTS += \
     server.o \
     servermgr.o \
     server_http.o \
+    server_udp.o \
     streamer_http.o \
+    streamer_udp.o \
     server_playlist.o \
     playlist.o \
     playlist_db.o \
@@ -503,7 +502,7 @@ BCM_DSGCC_CLIENTS_USE_SHARED_MEMORY_IPC = 0
 CFLAGS += -DMPOD_SUPPORT -DINTEGRATE_BCM_DSG_HOST
 POD_DIR = $(BSEAV)/cable/lib/mpod
 POD_STAGING_DIR = ${B_REFSW_OBJ_ROOT}/BSEAV/cable/lib/mpod
-ifeq ($(B_REFSW_ARCH),arm-linux)
+ifeq ($(filter ${B_REFSW_ARCH}, aarch64-linux arm-linux), ${B_REFSW_ARCH})
 CP_DIR = $(POD_DIR)/lib/cp_arm
 else
 CP_DIR = $(POD_DIR)/lib/cp
@@ -513,7 +512,7 @@ POD_DRIVERDIR = $(BSEAV)/cable/lib/mpod/src/driver/build/$(SYSTEM)
 
 LDFLAGS += -L${B_REFSW_OBJ_ROOT}/nexus/bin -lb_mpod
 LDFLAGS += -L$(POD_STAGING_DIR) -lcp
-ifeq ($(B_REFSW_ARCH),arm-linux)
+ifeq ($(filter ${B_REFSW_ARCH}, aarch64-linux arm-linux), ${B_REFSW_ARCH})
 ifeq ($(B_REFSW_TOOLCHAIN_VER_GE_4_8),y)
 LDFLAGS += -L$(POD_STAGING_DIR) -lcrypto
 else
@@ -553,7 +552,7 @@ else
 DOCSIS_CHIP = 3384
 endif
 
-ifeq ($(B_REFSW_ARCH),arm-linux)
+ifeq ($(filter ${B_REFSW_ARCH}, aarch64-linux arm-linux), ${B_REFSW_ARCH})
 export ARM_PLATFORM = yes
 else
 export ARM_PLATFORM = no
@@ -953,9 +952,12 @@ endif
 ## NETAPP (WiFi and Bluetooth) support
 ####
 ifeq ($(NETAPP_SUPPORT),y)
+include $(BSEAV)/connectivity/netapp.inc
 NETAPP_DIR = $(BSEAV)/../trellis/connectivity/netapp/build
 NETAPP_OUTPUT_DIR = ${B_REFSW_OBJ_ROOT}/BSEAV/bin
-FETCH_NETAPP_CMD := git clone ssh://$$USER@git-irv-02.irv.broadcom.com:29418/dev/trellis.git -b URSR-16.1
+INTERNAL_SERVER		:= git-irv-02.irv.broadcom.com
+FETCH_NETAPP_CMD 	:= repo init -u ssh://$(USER)@${INTERNAL_SERVER}:29418/AppLibs; repo sync
+SERVER_ALIVE        := $(shell nslookup -timeout=1 ${INTERNAL_SERVER} | grep Address && echo "1s" || echo "")
 
 ifneq ($(findstring clean,$(MAKECMDGOALS)), clean)
      include ${NETAPP_OUTPUT_DIR}/include/netapp.inc
@@ -977,9 +979,10 @@ export NEXUS_BIN_DIR:=${B_REFSW_OBJ_ROOT}/nexus/bin
 export NETAPP_IEEE1905=n
 export NETAPP_MIRACAST=n
 export NETAPP_SKIP_NEXUS_BUILD=y
-
-# What version of NetApp to pull
-export B_NETAPP_NAME=netapp_9.2
+export NETAPP_VOICE_RECOGNITION=n
+export NETAPP_ZEROCONF=n
+export NETAPP_DHCP=n
+export NETAPP_DHCPC=n
 endif
 
 ##########
@@ -1282,8 +1285,12 @@ ifeq ($(NETAPP_SUPPORT),y)
 # This builds and cleans the netapp libs
 ${NETAPP_OUTPUT_DIR}/include/netapp.inc :
 ifeq ($(wildcard ${NETAPP_DIR}),)
-	@echo "Fetching NetApp-API: [$(FETCH_NETAPP_CMD)]"
+	@echo "Fetching NetApp-API: [$(FETCH_NETAPP_CMD) Version:$(B_NETAPP_NAME)]"
 	@-cd $(BSEAV)/..; $(FETCH_NETAPP_CMD)
+endif
+ifneq (${SERVER_ALIVE},)
+	@-cd $(BSEAV)/../trellis; git fetch origin; git checkout $(B_NETAPP_NAME); git pull origin $(B_NETAPP_NAME)
+endif
 	@if [ ! -d ${NETAPP_DIR} ] ; then \
 		echo "======================================================================================================="; \
 		echo "               NETAPP-API Missing!";\
@@ -1292,7 +1299,6 @@ ifeq ($(wildcard ${NETAPP_DIR}),)
 		echo "";\
 		exit -1;\
 	fi
-endif
 	$(MAKE) -C $(NETAPP_DIR) install
 
 ifneq ($(NETAPP_BUILD_EXAMPLES),n)
@@ -1419,6 +1425,9 @@ ifeq ($(NEXUS_MODE),proxy)
 endif
 	$(Q_)$(CP) $(NEXUS_BIN_DIR)/logger $(STAGING_DIR)
 	$(Q_)$(CP) $(NEXUS_BIN_DIR)/nexus $(STAGING_DIR)
+ifeq ($(NXCLIENT_SUPPORT),y)
+	$(Q_)$(CP) $(NEXUS_BIN_DIR)/nxserver $(STAGING_DIR)
+endif
 	$(Q_)chmod +x $(STAGING_DIR)/nexus
 ifeq ($(CABLECARD_SUPPORT),y)
 	@$(CP) -fr $(NEXUS_BIN_DIR)/libb_mpod.so $(STAGING_DIR)
@@ -1511,6 +1520,8 @@ install-netapp-files:
 	@if [ -e $(ATLAS_BIN_DIR)/bin/dhd ];then $(CP) -fr $(ATLAS_BIN_DIR)/bin/dhd $(STAGING_DIR)/bin;fi
 	@if [ -e $(ATLAS_BIN_DIR)/bin/bcmdl ];then $(CP) -fr $(ATLAS_BIN_DIR)/bin/bcmdl $(STAGING_DIR)/bin;fi
 	@if [ -e $(ATLAS_BIN_DIR)/bin/bsa_server ];then $(CP) -fr $(ATLAS_BIN_DIR)/bin/bsa_server $(STAGING_DIR)/bin;fi
+	@if [ -e $(ATLAS_BIN_DIR)/bin/wpa_supplicant ];then $(CP) -fr $(ATLAS_BIN_DIR)/bin/wpa_supplicant $(STAGING_DIR)/bin;fi
+	@if [ -e $(ATLAS_BIN_DIR)/bin/wpa_supplicant.conf ];then $(CP) -fr $(ATLAS_BIN_DIR)/bin/wpa_supplicant.conf $(STAGING_DIR)/bin;fi
 	@if [ -e $(ATLAS_BIN_DIR)/bin/NetAppTester ];then $(CP) -fr $(ATLAS_BIN_DIR)/bin/NetAppTester $(STAGING_DIR)/bin;fi
 	@if [ -e $(ATLAS_BIN_DIR)/bin/app_manager ];then $(CP) -fr $(ATLAS_BIN_DIR)/bin/app_manager $(STAGING_DIR)/bin;fi
 	@if [ -e $(ATLAS_BIN_DIR)/bin/app_hh ];then $(CP) -fr $(ATLAS_BIN_DIR)/bin/app_hh $(STAGING_DIR)/bin;fi
@@ -1529,9 +1540,10 @@ install-netapp-files:
 	@if [ -e $(ATLAS_BIN_DIR)/lib/libwpsap.so ];then $(CP) -fr $(ATLAS_BIN_DIR)/lib/libwpsap.so $(STAGING_DIR)/lib;fi
 	@if [ -e $(ATLAS_BIN_DIR)/lib/libwpscli.so ];then $(CP) -fr $(ATLAS_BIN_DIR)/lib/libwpscli.so $(STAGING_DIR)/lib;fi
 	@if [ -e $(ATLAS_BIN_DIR)/lib/libbsa.so ];then $(CP) -fr $(ATLAS_BIN_DIR)/lib/libbsa.so $(STAGING_DIR)/lib;fi
-	@$(CP) -fr $(ATLAS_BIN_DIR)/lib/libcurl.so* $(STAGING_DIR)/lib
-	@$(CP) -fr $(ATLAS_BIN_DIR)/lib/libavahi-core.so* $(STAGING_DIR)/lib
-	@$(CP) -fr $(ATLAS_BIN_DIR)/lib/libavahi-common.so* $(STAGING_DIR)/lib
+	@if [ -e $(ATLAS_BIN_DIR)/lib/libcurl.so ];then $(CP) -fr $(ATLAS_BIN_DIR)/lib/libcurl.so* $(STAGING_DIR)/lib;fi
+	@if [ -e $(ATLAS_BIN_DIR)/lib/libavahi-core.so ];then $(CP) -fr $(ATLAS_BIN_DIR)/lib/libavahi-core.so* $(STAGING_DIR)/lib;fi
+	@if [ -e $(ATLAS_BIN_DIR)/lib/libavahi-common.so ];then $(CP) -fr $(ATLAS_BIN_DIR)/lib/libavahi-common.so* $(STAGING_DIR)/lib;fi
+	@if [ -e $(ATLAS_BIN_DIR)/lib/libnl-3.so ];then $(CP) -fr $(ATLAS_BIN_DIR)/lib/libnl*-3.so* $(STAGING_DIR)/lib;fi
 	@$(CP) -fr $(ATLAS_BIN_DIR)/lib/modules $(STAGING_DIR)/lib
 	@$(CP) -fr $(ATLAS_BIN_DIR)/firmware $(STAGING_DIR)
 else
@@ -1553,6 +1565,9 @@ install-config-files:
 		$(CP) ../channelmap/channels.xml $(STAGING_DIR)/channels.xml; \
 		fi; \
 	fi;
+	$(Q_)if [ -f ../channelmap/udpUrl.xml ] ; then  \
+		$(CP) ../channelmap/udpUrl.xml $(STAGING_DIR)/udpUrl.xml; \
+	fi;
 	@cd $(STAGING_DIR); chmod 664 atlas.cfg
 
 bin-install-config-files:
@@ -1566,6 +1581,9 @@ bin-install-config-files:
 		$(CP) ../channelmap/$(NEXUS_PLATFORM).channels.xml $(ATLAS_BIN_DIR)/channels.xml; \
 	else  \
 		$(CP) ../channelmap/channels.xml $(ATLAS_BIN_DIR)/channels.xml; \
+	fi;
+	$(Q_)if [ -f ../channelmap/udpUrl.xml ] ; then  \
+                $(CP) ../channelmap/udpUrl.xml $(ATLAS_BIN_DIR)/udpUrl.xml; \
 	fi;
 	@cd $(ATLAS_BIN_DIR); chmod 664 atlas.cfg
 	@echo [Install... fonts]
diff --git a/BSEAV/lib/protobuf/Makefile b/BSEAV/lib/protobuf/Makefile
--- a/BSEAV/lib/protobuf/Makefile
+++ b/BSEAV/lib/protobuf/Makefile
@@ -1,44 +1,43 @@
-#############################################################################
-#    (c)2010-2016 Broadcom Corporation
-#
-# This program is the proprietary software of Broadcom Corporation and/or its licensors,
-# and may only be used, duplicated, modified or distributed pursuant to the terms and
-# conditions of a separate, written license agreement executed between you and Broadcom
-# (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
-# no license (express or implied), right to use, or waiver of any kind with respect to the
-# Software, and Broadcom expressly reserves all rights in and to the Software and all
-# intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
-# HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
-# NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
-#
-# Except as expressly set forth in the Authorized License,
-#
-# 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
-# secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
-# and to use this information only in connection with your use of Broadcom integrated circuit products.
-#
-# 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
-# AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
-# WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
-# THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
-# OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
-# LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
-# OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
-# USE OR PERFORMANCE OF THE SOFTWARE.
-#
-# 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
-# LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
-# EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
-# USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
-# THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
-# ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
-# LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
-# ANY LIMITED REMEDY.
-#
-#
-#
-#############################################################################
-
+#******************************************************************************
+#* Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
+#*
+#* This program is the proprietary software of Broadcom and/or its
+#* licensors, and may only be used, duplicated, modified or distributed pursuant
+#* to the terms and conditions of a separate, written license agreement executed
+#* between you and Broadcom (an "Authorized License").  Except as set forth in
+#* an Authorized License, Broadcom grants no license (express or implied), right
+#* to use, or waiver of any kind with respect to the Software, and Broadcom
+#* expressly reserves all rights in and to the Software and all intellectual
+#* property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
+#* HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
+#* NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
+#*
+#* Except as expressly set forth in the Authorized License,
+#*
+#* 1. This program, including its structure, sequence and organization,
+#*    constitutes the valuable trade secrets of Broadcom, and you shall use all
+#*    reasonable efforts to protect the confidentiality thereof, and to use
+#*    this information only in connection with your use of Broadcom integrated
+#*    circuit products.
+#*
+#* 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
+#*    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
+#*    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
+#*    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
+#*    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
+#*    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
+#*    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
+#*    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
+#*
+#* 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
+#*    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
+#*    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
+#*    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
+#*    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
+#*    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
+#*    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
+#*    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
+#******************************************************************************/
 PWD := ${shell pwd}
 OPENSOURCE ?= ${PWD}/../
 THIS_DIR := BSEAV/lib/protobuf
@@ -72,7 +71,7 @@ PROTOBUF_SOURCE_PATH:=${PROTOBUF_SOURCE_DIRECTORY}/${PROTOBUF_NAME}
 PROTOBUF_TAR_PATH:=${PROTOBUF_SOURCE_DIRECTORY}
 PROTOBUF_BUILD_DIR:=$(abspath $(NEXUS_TOP)/../BSEAV/lib/protobuf)
 
-PROTOBUF_CFLAGS?= -O2 -fPIC
+PROTOBUF_CXXFLAGS?= -O2 -fPIC -Wno-unused-local-typedefs
 PROTOBUF_LDFLAGS?=
 PROTOBUF_DIR:=$(PROTOBUF_NAME)
 PROTOBUF_LIB_FOLDER:=${PROTOBUF_TAR_PATH}/${PROTOBUF_DIR}/$(NEXUS_PLATFORM)/lib
@@ -92,6 +91,53 @@ B_PROTOBUF_EXTRACT_REDIR :=
 ifeq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
     $(warning B_REFSW_PROTOBUF_IS_EXTERNAL=${B_REFSW_PROTOBUF_IS_EXTERNAL} Skipping build of Protobuf...)
 endif   #  ifeq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
+
+all : source
+	@if [ ! -d "${PROTOBUF_SOURCE_PATH}" ]; then \
+		echo "Protobuf source directory: $(abspath ${PROTOBUF_SOURCE_PATH}) not found, extracting from tarball..."  ${B_PROTOBUF_EXTRACT_REDIR}; \
+		if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_SOURCE_TARBALL}" ]; then \
+			echo "================ Downloading OPENSSL tarball  to ${PROTOBUF_TAR_PATH}"; \
+			mkdir -p ${PROTOBUF_TAR_PATH}; \
+			B_REFSW_CACHE_DIR=${B_REFSW_CACHE_DIR} $(NEXUS_TOP)/../BSEAV/tools/build/fetch.sh ${PROTOBUF_BUILD_DIR}/${PROTOBUF_NAME}.info ${PROTOBUF_TAR_PATH}; \
+		fi ;\
+	fi
+	@echo "================ Configuring PROTOBUF"
+	@if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/Makefile" ]; then \
+		echo "================ Configure PROTOBUF"; \
+		cd ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}; \
+		CXXFLAGS="${PROTOBUF_CXXFLAGS}" \
+		LDFLAGS="${PROTOBUF_LDFLAGS}" \
+		./configure \
+		--prefix=${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/${NEXUS_PLATFORM}${LOWER_BCHP_VER} \
+		--host=${B_PROTOBUF_TOOLCHAIN_ARCH} \
+		--disable-static\
+		--with-protoc=protoc\
+		--enable-shared; \
+		echo "================ PROTOBUF Configured"; \
+	fi
+
+	@if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/Makefile" ]; then \
+		echo "${PROTOBUF_NAME} is not configured!"; exit 1;\
+	fi
+
+	@echo "================ Compiling PROTOBUF==============================="
+	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME} -j10 ${MAKE_SUFFIX}
+	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/gtest -j10 ${MAKE_SUFFIX}
+	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME} install ${MAKE_SUFFIX}
+	@if [ "$(B_REFSW_DEBUG)" != 'y' ]; then \
+		${STRIP} ${PROTOBUF_LIB_FOLDER}/*.so; \
+	fi
+	@rm -rf protobuf_ver.inc
+	@echo "PROTOBUF_VER:="$(PROTOBUF_VER) >> protobuf_ver.inc
+	@echo "PROTOBUF_NAME:="$(PROTOBUF_NAME) >> protobuf_ver.inc
+	@echo "PROTOBUF_CFLAGS:="$(PROTOBUF_INC_CFLAGS) >> protobuf_ver.inc
+	@echo "PROTOBUF_LDFLAGS:="$(PROTOBUF_INC_LDFLAGS) >> protobuf_ver.inc
+	@echo "PROTOBUF_SOURCE_PATH:="$(PROTOBUF_SOURCE_PATH) >> protobuf_ver.inc
+	@echo "GTEST_CFLAGS:="$(GTEST_INC_CFLAGS) >> protobuf_ver.inc
+	@echo "GTEST_LDFLAGS:="$(GTEST_INC_LDFLAGS) >> protobuf_ver.inc
+	@echo "GTEST_SOURCE_PATH:="$(GTEST_SOURCE_PATH) >> protobuf_ver.inc
+	@echo "================ PROTOBUF Compiled!"
+	@touch $@
 
 source:
 ifneq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
@@ -128,54 +174,6 @@ endif   #  ifeq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
 #	@mkdir -p ${APPLIBS_TARGET_LIB_DIR}
 #	@mkdir -p ${APPLIBS_TARGET_INC_DIR}
 #	@cp -af $(PROTOBUF_TAR_PATH)/$(PROTOBUF_NAME)/src/.libs/*.so* ${APPLIBS_TARGET_LIB_DIR}
-
-all : source
-	@if [ ! -d "${PROTOBUF_SOURCE_PATH}" ]; then \
-		echo "Protobuf source directory: $(abspath ${PROTOBUF_SOURCE_PATH}) not found, extracting from tarball..."  ${B_PROTOBUF_EXTRACT_REDIR}; \
-		if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_SOURCE_TARBALL}" ]; then \
-			echo "================ Downloading OPENSSL tarball  to ${PROTOBUF_TAR_PATH}"; \
-			mkdir -p ${PROTOBUF_TAR_PATH}; \
-			B_REFSW_CACHE_DIR=${B_REFSW_CACHE_DIR} $(NEXUS_TOP)/../BSEAV/tools/build/fetch.sh ${PROTOBUF_BUILD_DIR}/${PROTOBUF_NAME}.info ${PROTOBUF_TAR_PATH}; \
-		fi ;\
-	fi
-	@echo "================ Configuring PROTOBUF"
-	@if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/Makefile" ]; then \
-		echo "================ Configure PROTOBUF"; \
-		cd ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}; \
-		CC=$(strip $(subst $(B_PROTOBUF_TOOLCHAIN_ARCH)-,,$(CC))) \
-		CFLAGS="${PROTOBUF_CFLAGS}" \
-		LDFLAGS="${PROTOBUF_LDFLAGS}" \
-		./configure \
-		--prefix=${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/${NEXUS_PLATFORM}${LOWER_BCHP_VER} \
-		--host=${B_PROTOBUF_TOOLCHAIN_ARCH} \
-		--disable-static\
-		--with-protoc= \
-		--enable-shared; \
-		echo "================ PROTOBUF Configured"; \
-	fi
-
-	@if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/Makefile" ]; then \
-		echo "${PROTOBUF_NAME} is not configured!"; exit 1;\
-	fi
-
-	@echo "================ Compiling PROTOBUF==============================="
-	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME} -j10 ${MAKE_SUFFIX}
-	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/gtest -j10 ${MAKE_SUFFIX}
-	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME} install ${MAKE_SUFFIX}
-	@if [ "$(B_REFSW_DEBUG)" != 'y' ]; then \
-		${STRIP} ${PROTOBUF_LIB_FOLDER}/*.so; \
-	fi
-	@rm -rf protobuf_ver.inc
-	@echo "PROTOBUF_VER:="$(PROTOBUF_VER) >> protobuf_ver.inc
-	@echo "PROTOBUF_NAME:="$(PROTOBUF_NAME) >> protobuf_ver.inc
-	@echo "PROTOBUF_CFLAGS:="$(PROTOBUF_INC_CFLAGS) >> protobuf_ver.inc
-	@echo "PROTOBUF_LDFLAGS:="$(PROTOBUF_INC_LDFLAGS) >> protobuf_ver.inc
-	@echo "PROTOBUF_SOURCE_PATH:="$(PROTOBUF_SOURCE_PATH) >> protobuf_ver.inc
-	@echo "GTEST_CFLAGS:="$(GTEST_INC_CFLAGS) >> protobuf_ver.inc
-	@echo "GTEST_LDFLAGS:="$(GTEST_INC_LDFLAGS) >> protobuf_ver.inc
-	@echo "GTEST_SOURCE_PATH:="$(GTEST_SOURCE_PATH) >> protobuf_ver.inc
-	@echo "================ PROTOBUF Compiled!"
-	@touch $@
 
 clean :
 	@echo "================ MAKE CLEAN"
