Broadcom Android Release 7.0 Phase 16.4 (eng 1) code drop
Change-Id: I57b7442cee44e2218a8de2f25d8aab4914f8a6f7

diff --git a/BSEAV/lib/protobuf/Makefile b/BSEAV/lib/protobuf/Makefile
--- a/BSEAV/lib/protobuf/Makefile
+++ b/BSEAV/lib/protobuf/Makefile
@@ -1,40 +1,41 @@
-###############################################################################
-# Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
+############################################################
+#  Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 #
-# This program is the proprietary software of Broadcom and/or its licensors,
-# and may only be used, duplicated, modified or distributed pursuant to the terms and
-# conditions of a separate, written license agreement executed between you and Broadcom
-# (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
-# no license (express or implied), right to use, or waiver of any kind with respect to the
-# Software, and Broadcom expressly reserves all rights in and to the Software and all
-# intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
-# HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
-# NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
+#  This program is the proprietary software of Broadcom and/or its licensors,
+#  and may only be used, duplicated, modified or distributed pursuant to the terms and
+#  conditions of a separate, written license agreement executed between you and Broadcom
+#  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
+#  no license (express or implied), right to use, or waiver of any kind with respect to the
+#  Software, and Broadcom expressly reserves all rights in and to the Software and all
+#  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
+#  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
+#  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 #
-# Except as expressly set forth in the Authorized License,
+#  Except as expressly set forth in the Authorized License,
 #
-# 1.     This program, including its structure, sequence and organization, constitutes the valuable trade
-# secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
-# and to use this information only in connection with your use of Broadcom integrated circuit products.
+#  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
+#  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
+#  and to use this information only in connection with your use of Broadcom integrated circuit products.
 #
-# 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
-# AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
-# WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
-# THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
-# OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
-# LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
-# OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
-# USE OR PERFORMANCE OF THE SOFTWARE.
+#  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
+#  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
+#  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
+#  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
+#  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
+#  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
+#  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
+#  USE OR PERFORMANCE OF THE SOFTWARE.
 #
-# 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
-# LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
-# EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
-# USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
-# THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
-# ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
-# LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
-# ANY LIMITED REMEDY.
-##############################################################################
+#  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
+#  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
+#  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
+#  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
+#  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
+#  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
+#  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
+#  ANY LIMITED REMEDY.
+#
+############################################################
 PWD := ${shell pwd}
 OPENSOURCE ?= ${PWD}/../
 THIS_DIR := BSEAV/lib/protobuf
@@ -46,43 +47,23 @@ NEXUS_TOP := $(B_REFSW_TOP)/nexus
 # include cross-compiler definitions
 include ${NEXUS_TOP}/platforms/common/build/platform_app.inc
 include ${NEXUS_TOP}/platforms/common/build/nexus_platforms.inc
+include protobuf.inc
 
 $(if $(NEXUS_PLATFORM),,  $(error ERROR: NEXUS_PLATFORM is not defined))
 $(if $(B_REFSW_ARCH),,    $(error ERROR: B_REFSW_ARCH is not defined))
 
-B_REFSW_DEBUG ?= y
-ifeq ($(B_REFSW_DEBUG),y)
-    DEBUG_SUFFIX=debug
-else
-    DEBUG_SUFFIX=release
-endif
-
 B_PROTOBUF_TOOLCHAIN_ARCH ?= $(B_REFSW_ARCH)
 
-PROTOBUF_VER?=2.5.0
-PROTOBUF_NAME=protobuf-$(PROTOBUF_VER)
-
 PROTOC_VER := $(shell protoc --version | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
-PROTOBUF_SOURCE_TARBALL:=$(PROTOBUF_NAME).tar.bz2
-PROTOBUF_SOURCE_DIRECTORY:=$(abspath $(B_REFSW_OBJ_ROOT)/BSEAV/lib/protobuf/$(B_REFSW_ARCH).$(DEBUG_SUFFIX))
-PROTOBUF_SOURCE_PATH:=${PROTOBUF_SOURCE_DIRECTORY}/${PROTOBUF_NAME}
-PROTOBUF_TAR_PATH:=${PROTOBUF_SOURCE_DIRECTORY}
-PROTOBUF_BUILD_DIR:=$(abspath $(NEXUS_TOP)/../BSEAV/lib/protobuf)
+ifeq ("$(PROTOC_VER)", "$(PROTOBUF_VER)")
+    PROTOC_COMMAND := protoc
+else
+    PROTOC_COMMAND := $(B_REFSW_OBJ_ROOT)/BSEAV/lib/protobuf/$(B_REFSW_ARCH).$(DEBUG_SUFFIX)/protobuf-$(PROTOBUF_VER)/host/bin/protoc
+endif
 
-PROTOBUF_CXXFLAGS?= -O2 -fPIC -Wno-unused-local-typedefs
-PROTOBUF_LDFLAGS?=
-PROTOBUF_DIR:=$(PROTOBUF_NAME)
-PROTOBUF_LIB_FOLDER:=${PROTOBUF_TAR_PATH}/${PROTOBUF_DIR}/$(NEXUS_PLATFORM)/lib
+PROTOBUF_CONFIG_CXXFLAGS?= -O2 -fPIC -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-return-type
 
-PROTOBUF_INC_CFLAGS:= -D_REENTRANT -I${PROTOBUF_TAR_PATH}/${PROTOBUF_DIR}/$(NEXUS_PLATFORM)/include
-PROTOBUF_INC_LDFLAGS:= -L$(PROTOBUF_LIB_FOLDER) -lprotobuf
-GTEST_SOURCE_PATH:=$(PROTOBUF_SOURCE_PATH)/gtest
-GTEST_LIB_FOLDER:=${PROTOBUF_TAR_PATH}/${PROTOBUF_DIR}/gtest/lib/.libs/
-GTEST_INC_CFLAGS:= -D_REENTRANT -I${PROTOBUF_TAR_PATH}/${PROTOBUF_DIR}/gtest/include
-GTEST_INC_LDFLAGS:= -L$(GTEST_LIB_FOLDER) -lgtest
-
-
-.PHONY: source all clean prerequisite
+.PHONY: source all clean
 
 B_PROTOBUF_EXTRACT_REDIR :=
 
@@ -90,26 +71,41 @@ ifeq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
     $(warning B_REFSW_PROTOBUF_IS_EXTERNAL=${B_REFSW_PROTOBUF_IS_EXTERNAL} Skipping build of Protobuf...)
 endif   #  ifeq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
 
-all : source
-	@if [ ! -d "${PROTOBUF_SOURCE_PATH}" ]; then \
-		echo "Protobuf source directory: $(abspath ${PROTOBUF_SOURCE_PATH}) not found, extracting from tarball..."  ${B_PROTOBUF_EXTRACT_REDIR}; \
-		if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_SOURCE_TARBALL}" ]; then \
-			echo "================ Downloading OPENSSL tarball  to ${PROTOBUF_TAR_PATH}"; \
-			mkdir -p ${PROTOBUF_TAR_PATH}; \
-			B_REFSW_CACHE_DIR=${B_REFSW_CACHE_DIR} $(NEXUS_TOP)/../BSEAV/tools/build/fetch.sh ${PROTOBUF_BUILD_DIR}/${PROTOBUF_NAME}.info ${PROTOBUF_TAR_PATH}; \
-		fi ;\
+build_protoc: source
+ifneq ($(PROTOBUF_VER), $(PROTOC_VER))
+	@echo "================ Configuring PROTOBUF for build server"
+	@if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/Makefile" ]; then \
+		echo "================ Configure PROTOBUF"; \
+		cd ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}; \
+                CXXFLAGS="${PROTOBUF_CONFIG_CXXFLAGS}" \
+		./configure \
+		--prefix=${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/host \
+		--disable-shared; \
+		echo "================ PROTOBUF Configured"; \
 	fi
+	@echo "================ Building protoc for build server"
+	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME} -j10 ${MAKE_SUFFIX}
+	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME} install ${MAKE_SUFFIX}
+	@if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/host/bin/protoc" ]; then \
+		echo "Filed to build protoc!"; exit 1; \
+	fi
+	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME} distclean ${MAKE_SUFFIX}
+	@echo "================ protoc for build server was built"
+else
+	@echo "================ Use protoc installed in build server"
+endif # ifneq ($(PROTOBUF_VER), $(PROTOC_VER))
+
+all : build_protoc
 	@echo "================ Configuring PROTOBUF"
 	@if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/Makefile" ]; then \
 		echo "================ Configure PROTOBUF"; \
 		cd ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}; \
-		CXXFLAGS="${PROTOBUF_CXXFLAGS}" \
-		LDFLAGS="${PROTOBUF_LDFLAGS}" \
+		CXXFLAGS="${PROTOBUF_CONFIG_CXXFLAGS}" \
 		./configure \
 		--prefix=${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME}/${NEXUS_PLATFORM}${LOWER_BCHP_VER} \
 		--host=${B_PROTOBUF_TOOLCHAIN_ARCH} \
-		--disable-static\
-		--with-protoc=protoc\
+		--enable-static \
+		--with-protoc=${PROTOC_COMMAND} \
 		--enable-shared; \
 		echo "================ PROTOBUF Configured"; \
 	fi
@@ -124,29 +120,12 @@ all : source
 	${MAKE} ${MAKE_OPTIONS} -C ${PROTOBUF_TAR_PATH}/${PROTOBUF_NAME} install ${MAKE_SUFFIX}
 	@if [ "$(B_REFSW_DEBUG)" != 'y' ]; then \
 		${STRIP} ${PROTOBUF_LIB_FOLDER}/*.so; \
+                ${STRIP} $(GTEST_LIB_FOLDER)/*.so; \
 	fi
-	@rm -rf protobuf_ver.inc
-	@echo "PROTOBUF_VER:="$(PROTOBUF_VER) >> protobuf_ver.inc
-	@echo "PROTOBUF_NAME:="$(PROTOBUF_NAME) >> protobuf_ver.inc
-	@echo "PROTOBUF_CFLAGS:="$(PROTOBUF_INC_CFLAGS) >> protobuf_ver.inc
-	@echo "PROTOBUF_LDFLAGS:="$(PROTOBUF_INC_LDFLAGS) >> protobuf_ver.inc
-	@echo "PROTOBUF_SOURCE_PATH:="$(PROTOBUF_SOURCE_PATH) >> protobuf_ver.inc
-	@echo "GTEST_CFLAGS:="$(GTEST_INC_CFLAGS) >> protobuf_ver.inc
-	@echo "GTEST_LDFLAGS:="$(GTEST_INC_LDFLAGS) >> protobuf_ver.inc
-	@echo "GTEST_SOURCE_PATH:="$(GTEST_SOURCE_PATH) >> protobuf_ver.inc
 	@echo "================ PROTOBUF Compiled!"
 	@touch $@
 
-prerequisite:
-ifneq ("$(PROTOC_VER)", "$(PROTOBUF_VER)")
-	@echo " "
-	@echo -e "\e[1;33mYour protoc version is not expected as 2.5.0, please ask your Admin to install correct version of protoc in build server $<\e[0m"
-	@echo " "
-	@exit 1 > /dev/null
-	@echo " "
-endif
-
-source: prerequisite
+source:
 ifneq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
 	@if [ ! -d "${PROTOBUF_SOURCE_PATH}" ]; then \
 		echo ""; \
@@ -155,36 +134,29 @@ ifneq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
 		echo "PROTOBUF_SOURCE_DIRECTORY is ${PROTOBUF_SOURCE_DIRECTORY}"; \
 		echo "$(B_REFSW_ARCH).$(DEBUG_SUFFIX)"; \
 		if [ ! -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_SOURCE_TARBALL}" ]; then \
-			echo "================ Downloading OPENSSL tarball  to ${PROTOBUF_TAR_PATH}"; \
+			echo "================ Downloading PROTOBUF tarball  to ${PROTOBUF_TAR_PATH}"; \
 			mkdir -p ${PROTOBUF_TAR_PATH}; \
-			echo "${PROTOBUF_BUILD_DIR}/${PROTOBUF_NAME}"; \
-			echo "${PROTOBUF_TAR_PATH}"; \
 			B_REFSW_CACHE_DIR=${B_REFSW_CACHE_DIR} $(NEXUS_TOP)/../BSEAV/tools/build/fetch.sh ${PROTOBUF_BUILD_DIR}/${PROTOBUF_NAME}.info ${PROTOBUF_TAR_PATH}; \
 		fi ;\
 		if [ -e "${PROTOBUF_TAR_PATH}/${PROTOBUF_SOURCE_TARBALL}" ]; then \
 			echo "================ Extracting PROTOBUF tarball"; \
-			echo "${PROTOBUF_SOURCE_PATH}"; \
 			mkdir -p ${PROTOBUF_SOURCE_PATH}; \
-			echo "PROTOBUF_TAR_PATH is ${PROTOBUF_TAR_PATH}"; \
-			echo "PROTOBUF_SOURCE_TARBALL is ${PROTOBUF_SOURCE_TARBALL}"; \
-			tar -jxf ${PROTOBUF_TAR_PATH}/${PROTOBUF_SOURCE_TARBALL} -C ${PROTOBUF_SOURCE_PATH}/..; \
+			tar -xf ${PROTOBUF_TAR_PATH}/${PROTOBUF_SOURCE_TARBALL} -C ${PROTOBUF_SOURCE_PATH}/..; \
 		else \
 			echo "Tarball ${PROTOBUF_TAR_PATH}/${PROTOBUF_SOURCE_TARBALL} is missing"; exit 1;\
 		fi ${B_PROTOBUF_EXTRACT_REDIR};\
 	fi
 endif   #  ifeq ($(B_REFSW_PROTOBUF_IS_EXTERNAL),y)
 
-#install: all
-#	@echo "================ Installing PROTOBUF"
-#	@echo "APPLIBS_TARGET_LIB_DIR is ${APPLIBS_TARGET_LIB_DIR}"
-#	@echo "APPLIBS_TARGET_INC_DIR is ${APPLIBS_TARGET_INC_DIR}"
-#	@mkdir -p ${APPLIBS_TARGET_LIB_DIR}
-#	@mkdir -p ${APPLIBS_TARGET_INC_DIR}
-#	@cp -af $(PROTOBUF_TAR_PATH)/$(PROTOBUF_NAME)/src/.libs/*.so* ${APPLIBS_TARGET_LIB_DIR}
+install_to_nexus_bin: all
+	@echo "================ Installing PROTOBUF to ${NEXUS_BIN_DIR}"
+	@mkdir -p ${NEXUS_BIN_DIR}
+	@install -c -m 0755 $(PROTOBUF_LIB_FOLDER)/*.so* ${NEXUS_BIN_DIR}
+	@install -c -m 0755 $(GTEST_LIB_FOLDER)/*.so* ${NEXUS_BIN_DIR}
 
 clean :
 	@echo "================ MAKE CLEAN"
-	@rm -rf protobuf_ver.inc
+	@rm -rf .libs
 	@rm -rf ${PROTOBUF_TAR_PATH}
 	@rm -rf all
 	@echo "================ Done"
